# Generated by Django 3.2.7 on 2021-10-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_producer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='producer',
            field=models.CharField(default='Не указан', max_length=255),
        ),
    ]
